spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

# JdbcTemplate 쿼리 확인
logging:
  level:
    hello:
      itemservice:
        repository:
          mybatis: trace
    org:
      springframework:
        jdbc: debug

mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true
