spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

# JdbcTemplate 쿼리 확인
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

      springframework:
        jdbc: debug

    hello:
      itemservice:
        repository:
          mybatis: trace

mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/**/*.xml XML파일을 원하는 위치에 두고 싶을 때 설정
